In [2]:
#importing numpy
import numpy as np
#importing pandas
import pandas as pd

In [3]:
#1-D array
a1=np.array([1,2,3])
#2-D array
a2=np.array([[1,2,3],[4,5,6]])
#3-D array
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])

In [4]:
#shape of n-array
a1.shape,a2.shape,a3.shape

((3,), (2, 3), (3, 3, 3))

In [5]:
#type of n-array
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [6]:
#data type of n-array
a1.dtype,a2.dtype,a3.dtype

(dtype('int32'), dtype('int32'), dtype('int32'))

In [7]:
#dimension of n-array
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [8]:
#creating dataframe
df1=pd.DataFrame(a1)
df2=pd.DataFrame(a2)
df3=pd.DataFrame(a3)

ValueError: Must pass 2-d input. shape=(3, 3, 3)

In [10]:
#Ones n-array
ones1=np.ones((10,2))
ones1

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
#zeroes n-array
zeroes1=np.zeros((7,2,3))
zeroes1

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [12]:
#1-D random array ranging 0-100 and size(7,2)
array1=np.random.randint(0,100,size=(7,2))
array1

array([[50, 94],
       [11, 98],
       [11,  6],
       [90, 92],
       [28, 83],
       [65, 72],
       [38,  8]])

In [13]:
#random array of size(3,5) ranging 0-1
array2=np.random.rand(3,5)
array2

array([[0.06010747, 0.00854056, 0.86969078, 0.46666773, 0.51645868],
       [0.25635333, 0.57886854, 0.86966016, 0.53041307, 0.47882231],
       [0.25139409, 0.13209952, 0.7416757 , 0.11397681, 0.88330348]])

In [14]:
#array of ranging 0-100
array3=np.arange(0,100)
array3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [15]:
#setting seed
#array of (4,6) ranging 0,10
np.random.seed(42)
array4=np.random.randint(0,10,size=(4,6))
array4

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [16]:
#0th index of array4
array4[0]

array([6, 3, 7, 4, 6, 9])

In [17]:
#first two rows of array4
array4[:2,:]

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7]])

In [18]:
# Get the first 2 values of the first 2 rows of array4
array4[:2,:2]

array([[6, 3],
       [2, 6]])

In [19]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
np.random.seed(42)
array5=np.random.randint(0,10,size=(3,5))
ones2=np.ones((3,5))
array5,ones2

(array([[6, 3, 7, 4, 6],
        [9, 2, 6, 7, 4],
        [3, 7, 7, 2, 5]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [20]:
#summation of array
array5+ones2

array([[ 7.,  4.,  8.,  5.,  7.],
       [10.,  3.,  7.,  8.,  5.],
       [ 4.,  8.,  8.,  3.,  6.]])

In [21]:
# Create another array of ones of shape (5, 3)
ones3=np.ones((5,3))

In [22]:
array5+ones3

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [24]:
#resahping the array
ones3=np.reshape(ones3,(3,5))

In [25]:
# Subtract the new array of ones from the other most recent array
array5-ones3

array([[5., 2., 6., 3., 5.],
       [8., 1., 5., 6., 3.],
       [2., 6., 6., 1., 4.]])

In [26]:
# Multiply the ones array with the latest array
array5*ones3

array([[6., 3., 7., 4., 6.],
       [9., 2., 6., 7., 4.],
       [3., 7., 7., 2., 5.]])

In [27]:
# Take the latest array to the power of 2 using '**'
array5**2

array([[36,  9, 49, 16, 36],
       [81,  4, 36, 49, 16],
       [ 9, 49, 49,  4, 25]], dtype=int32)

In [28]:
# Do the same thing with np.square()
np.square(array5)

array([[36,  9, 49, 16, 36],
       [81,  4, 36, 49, 16],
       [ 9, 49, 49,  4, 25]], dtype=int32)

In [29]:
# mean of the latest array 
np.mean(array2)

0.45053548243816977

In [30]:
#max of array
np.max(array2)

0.8833034834526503

In [31]:
#min of array
np.min(array2)

0.008540562841539368

In [32]:
#standard deviation
np.std(array2)

0.2934273602669681

In [33]:
#variance 
np.var(array2)

0.08609961575324108

In [34]:
# Transpose the latest array
array6=array5.T
array6,array5

(array([[6, 9, 3],
        [3, 2, 7],
        [7, 6, 7],
        [4, 7, 2],
        [6, 4, 5]]),
 array([[6, 3, 7, 4, 6],
        [9, 2, 6, 7, 4],
        [3, 7, 7, 2, 5]]))

In [35]:
np.random.seed(4)
array7=np.random.randint(0,10,size=(3,3))
array8=np.random.randint(0,10,size=(3,3))

In [36]:
np.dot(array7,array8)

array([[ 95,  73,  76],
       [160, 116, 110],
       [128,  78,  57]])

In [37]:
np.random.seed(4)
array9=np.random.randint(0,10,size=(4,3))
array9=array9.T
np.dot(array7,array9)

array([[ 75,  99,  66,  93],
       [ 99, 177, 135, 177],
       [ 66, 135, 134, 140]])

In [38]:
array7>array8

array([[False, False, False],
       [False,  True,  True],
       [False,  True,  True]])

In [39]:
array7>=7

array([[ True, False, False],
       [ True,  True,  True],
       [False,  True,  True]])

In [40]:
array7==array8

array([[ True, False, False],
       [ True, False, False],
       [False, False, False]])

In [41]:
np.sort(array7)

array([[1, 5, 7],
       [7, 8, 8],
       [2, 7, 9]])

In [42]:
np.argsort(array7)

array([[2, 1, 0],
       [1, 0, 2],
       [0, 2, 1]], dtype=int32)

In [43]:
np.argmin(array7,axis=1)

array([2, 1, 0], dtype=int32)

In [44]:
np.argmin(array7,axis=0)

array([2, 0, 0], dtype=int32)

In [45]:
array10=np.arange(0,100,10)
array10

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [46]:
np.random.seed(4)
array11=np.random.normal(0,100,size=(5,2))
array11

array([[   5.05617071,   49.99513332],
       [ -99.59089311,   69.35985083],
       [ -41.830152  , -158.45772351],
       [ -64.77067671,   59.8575174 ],
       [  33.22500326, -114.74766329]])

In [47]:
array11.nbytes

80

In [48]:
array11.itemsize

8

In [49]:
array11[-1]

array([  33.22500326, -114.74766329])

In [50]:
array11[0,1]

49.995133323782895

In [51]:
array11[0,1]=49.5
array11

array([[   5.05617071,   49.5       ],
       [ -99.59089311,   69.35985083],
       [ -41.830152  , -158.45772351],
       [ -64.77067671,   59.8575174 ],
       [  33.22500326, -114.74766329]])

In [52]:
array11[::-5]

array([[  33.22500326, -114.74766329]])

In [53]:
array11[:2,::1]

array([[  5.05617071,  49.5       ],
       [-99.59089311,  69.35985083]])

In [54]:
array11_copy=array11[:3,:3]
array11_copy

array([[   5.05617071,   49.5       ],
       [ -99.59089311,   69.35985083],
       [ -41.830152  , -158.45772351]])

In [55]:
array11[np.newaxis,:]

array([[[   5.05617071,   49.5       ],
        [ -99.59089311,   69.35985083],
        [ -41.830152  , -158.45772351],
        [ -64.77067671,   59.8575174 ],
        [  33.22500326, -114.74766329]]])

In [56]:
#size must be same
np.concatenate([array7,array8])

array([[7, 5, 1],
       [8, 7, 8],
       [2, 9, 7],
       [7, 7, 9],
       [8, 4, 2],
       [6, 4, 3]])

In [57]:
np.concatenate([array7,array8],axis=1)

array([[7, 5, 1, 7, 7, 9],
       [8, 7, 8, 8, 4, 2],
       [2, 9, 7, 6, 4, 3]])

In [58]:
x=np.array([1,2,3,4,5,5])
np.vstack([x,array7])


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 6 and the array at index 1 has size 3

In [59]:
#splitting the array
np.split(x,[1,4])

[array([1]), array([2, 3, 4]), array([5, 5])]

In [61]:
#complex arrays
array12=np.array([[1,2],[3,4]],dtype=complex)
array12

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [67]:
#empty creates an array whose initial content is random and depends on the state of the memory
np.empty( (2,3) )

array([[  5.05617071,  49.5       ,  99.59089311],
       [ 69.35985083,  41.830152  , 158.45772351]])

In [68]:
# linspace that receives as an argument the number of elements that we want
np.linspace(1,10,5)
np.linespace(0,2)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [70]:
sine=np.sin(x)
sine

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.95892427])

In [79]:
#@ for matrix multiplication
array5.shape
ones3=ones3.reshape(5,3)
array5 @ ones3

array([[26., 26., 26.],
       [28., 28., 28.],
       [24., 24., 24.]])

In [81]:
array5*=3
array5

array([[54, 27, 63, 36, 54],
       [81, 18, 54, 63, 36],
       [27, 63, 63, 18, 45]])

In [84]:
for i in array5:
    print(i**(3))

[157464  19683 250047  46656 157464]
[531441   5832 157464 250047  46656]
[ 19683 250047 250047   5832  91125]


In [87]:
for i in array5.flat:
    print(i)

54
27
63
36
54
81
18
54
63
36
27
63
63
18
45


In [88]:
## returns the array, flattened
array5.ravel()

array([54, 27, 63, 36, 54, 81, 18, 54, 63, 36, 27, 63, 63, 18, 45])

In [91]:
np.column_stack((array5,ones3))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 5